// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4Nq7lySdeSs9Rf1b_u13Yd5ZrMo7qmCI',
    appId: '1:637554243830:web:39110361bdc4baeaf254d7',
    messagingSenderId: '637554243830',
    projectId: 'found-81d42',
    authDomain: 'found-81d42.firebaseapp.com',
    storageBucket: 'found-81d42.firebasestorage.app',
    measurementId: 'G-X506B2RXYF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjGvi9qlnIiiCHPm-hyTlE3IPX2Lx9GYg',
    appId: '1:637554243830:android:07913669f348d078f254d7',
    messagingSenderId: '637554243830',
    projectId: 'found-81d42',
    storageBucket: 'found-81d42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA79A4EEScyzYrMdmG83d1F_uJXFjEN0bU',
    appId: '1:637554243830:ios:a519017b45d86442f254d7',
    messagingSenderId: '637554243830',
    projectId: 'found-81d42',
    storageBucket: 'found-81d42.firebasestorage.app',
    iosBundleId: 'com.csc2074g16.found404',
  );
}
