import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'dart:io' show Platform;
import 'package:flutter/foundation.dart' show kIsWeb, TargetPlatform, defaultTargetPlatform;

/// Placeholder generated-file stand-in.
///
/// This file is normally auto-generated by running:
///
///   dart pub global activate flutterfire_cli
///   flutterfire configure
///
/// against a real Firebase project, which fills in [currentPlatform] with
/// real API keys/app ids per platform. No Firebase project has been created
/// for this repo yet (see README "Firebase setup"), so this stub throws a
/// clear error instead of silently connecting nowhere. Once a teammate runs
/// `flutterfire configure`, let it overwrite this file — do not hand-edit
/// the generated options in afterward.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw _notConfigured('web');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw _notConfigured('android');
      case TargetPlatform.iOS:
        throw _notConfigured('ios');
      default:
        throw _notConfigured(Platform.operatingSystem);
    }
  }

  static UnsupportedError _notConfigured(String platform) {
    return UnsupportedError(
      'Firebase has not been configured for $platform yet.\n'
      'Run `flutterfire configure` against the team Firebase project to '
      'generate a real lib/firebase_options.dart. See README.md > Firebase setup.',
    );
  }
}
